version: "3.9"
services:
  jupyter:
    # 既にDockerfileからイメージをビルド済みであればimage:に指定する。
    image: python_3.11:v1
    # build:
    #  context: ./jupyter
    #  dockerfile: Dockerfile
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/work
    expose:
      - "8888"
    ports:
      - "0.0.0.0:8888:8888"
    volumes:
      - ./jupyter/jupyter-config:/root/.jupyter
      - ~/work/git_work/:/work
